<?php

/**
 * @file
 * Install, update and uninstall functions for pece_frontpage_slideshow module.
 */

/**
 * Update Slideshow settings for Home page.
 */
function pece_frontpage_slideshow_update_7001() {
  module_load_include('inc', 'pece', 'pece.functions');

  // Revert views_default_views default config.
  pece_defaultconfig_component_rebuild_by_name('views_default_views', 'pece_frontpage_slideshow');
}
