<?php
/**
 * @file
 * pece_api.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function pece_api_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'services_security_update_1';
  $strongarm->value = TRUE;
  $export['services_security_update_1'] = $strongarm;

  return $export;
}
