<?php

/**
 * @file
 * Code for the PECE Tests module.
 */

/**
 * Implements hook_seeds_seed_[TYPE]_[ACTION]_result_alter().
 */
function pece_tests_seeds_seed_user_create_result_alter(&$result, $context, $type) {
  // Handle legal terms acceptance.
  if (isset($result->uid) && !empty($context['config']['accept_legal_terms'])) {
    $conditions = legal_get_conditions($language->language);
    legal_save_accept($conditions['version'], $conditions['revision'], $conditions['language'], $result->uid);
  }
}
