<?php
/**
 * @file
 * Code for the PECE Artifacts feature.
 */

include_once 'pece_artifacts.features.inc';

/**
 * Implements hook_pece_artifact_info().
 */
function pece_artifacts_pece_artifact_info($only_enabled = TRUE) {
  $node_types = node_type_get_types();
  $artifacts = array();
  $prefix = 'pece_artifact_';

  foreach ($node_types as $node_type => $node_type_info) {
    $is_artifact = substr($node_type, 0, strlen($prefix)) == $prefix;
    if ($is_artifact && (!$only_enabled || !$node_type_info->disabled)) {
      $artifacts[$node_type] = $node_type;
    }
  }

  return $artifacts;
}

/**
 * Implements hook_form_alter().
 */
function pece_artifacts_form_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'pece_artifacts', 'pece_artifacts.functions');

  $artifacts = pece_artifacts_fetch_all();
  $is_node_form = !empty($form['#node_edit_form']) && isset($form['#node']->type);
  $is_artifact_form = $is_node_form && in_array($form['#node']->type, $artifacts);

  if ($is_artifact_form) {
    _pece_artifacts_form_pece_artifact_form_alter($form, $form_state);
  }
}

/**
 * Default form alter for PECE's artifacts.
 */
function _pece_artifacts_form_pece_artifact_form_alter(&$form, &$form_state) {
  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
  // We cannot allow the content to be authored by anonymous.
  $form['author']['name']['#required'] = TRUE;

  // Hide/show location fieldset based on fieldsite location usage flag.
  if (!empty($form['field_pece_use_fieldsite_local'])) {
    $form['field_pece_location']['#states']['visible']['#edit-field-use-fieldsite-location input'] = array(
      'checked' => FALSE,
    );
  }
}

/**
 * Implements hook_node_presave().
 */
function pece_artifacts_node_presave($node) {
  module_load_include('inc', 'pece_artifacts', 'pece_artifacts.functions');

  $artifacts = pece_artifacts_fetch_all();

  if (in_array($node->type, $artifacts)) {
    $use_fieldsite_location = field_get_items('node', $node, 'field_pece_use_fieldsite_local');
    if (!empty($use_fieldsite_location[0]['value'])) {
      // Remove any current data from the artifact's location field.
      $node->field_pece_location[LANGUAGE_NONE] = array();

      $fieldsite_field = field_get_items('node', $node, 'field_pece_fieldsite');
      if (!empty($fieldsite_field[0]['target_id'])) {
        $fieldsite = node_load($fieldsite_field[0]['target_id']);
        $node->field_pece_location = $fieldsite->field_pece_location;
      }
    }
  }
}

/**
 * Implements hook_node_update().
 */
function pece_artifacts_node_update($node) {
  if ($node->type == 'pece_fieldsite') {
    $location = field_get_items('node', $node, 'field_pece_location');
    if (!empty($location)) {
      module_load_include('inc', 'pece_artifacts', 'pece_artifacts.functions');

      $artifacts = pece_artifacts_fetch_all();

      $query = new EntityFieldQuery();
      $result = $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', $artifacts)
        ->fieldCondition('field_pece_fieldsite', 'target_id', $node->nid)
        ->fieldCondition('field_pece_use_fieldsite_local', 'value', TRUE)
        ->execute();

      if (isset($result['node'])) {
        // Execution time cache is not clean until after this hook is performed; although
        // the node's data is already saved to the database.
        entity_get_controller('node')->resetCache(array($node->nid));

        $artifacts_ids = array_keys($result['node']);
        $artifacts = entity_load('node', $artifacts_ids);
        foreach ($artifacts as $artifact) {
          node_save($artifact);
        }
      }
    }
  }
}
