version: '3'

services:
  mariadb:
    networks:
      pecev1:

  php:
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1

networks:
  pecev1:
    external:
      name: pecev1
