<?php
/**
 * @file
 * Code for the pece_artifacts_image feature.
 */

include_once 'pece_artifacts_image.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_artifacts_image_form_pece_artifact_image_node_form_alter(&$form, &$form_state) {
  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
  // We cannot allow the content to be authored by anonymous.
  $form['author']['name']['#required'] = TRUE;

  if (module_exists('pece_profile')) {
    array_unshift($form['#validate'], '_pece_artifact_image_check_author');
  }
}

/**
 * Implements hook_modules_enabled().
 *
 * This hook is implemented to assign some default permissions for PECE's image
 * artifact.
 * This has to be done in this hook to run after both features
 * and defaultconfig which power the functionality. Hopefully a more general
 * solution can be found. More information - http://drupal.org/node/1837312.
 */
function pece_artifacts_image_modules_enabled($modules) {

  // Only run this logic if we are executing as part of an install profile
  // and only for this particular module.
  if (drupal_installation_attempted() && in_array('pece_artifacts_image', $modules)) {

    $perms = array(
      'create pece_artifact_image content',
      'delete own pece_artifact_image content',
      'edit own pece_artifact_image content',
    );

    foreach ($perms as $perm) {
      // Define some permissions for the authentcated user role
      user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array($perm));
    }
  }
}

/**
 * Validate function to check the authors field and fill the contributors
 * accourding the author name.
 */
function _pece_artifact_image_check_author(&$form, &$form_state) {

  if (!isset($user_profile['pece_profile_main'])) {
    return;
  }

  global $user;

  $values = $form_state['values'];
  $user_profile = profile2_load_by_user($user);
  $contributor_role = user_role_load_by_name('Contributor');

  $profile_wrapper = entity_metadata_wrapper('profile2', $user_profile['pece_profile_main']);

  if (in_array($contributor_role->rid, array_keys($user->roles) &&
      isset($values['field_pece_authors']['und'][0]) &&
      $values['field_pece_authors']['und'][0]['name'] != $profile_wrapper->field_pece_full_name->value())) {

    $value = array(LANGUAGE_NONE => array(array('target_id' => $user->uid)));
    form_set_value($form['field_pece_contributors'], $value, $form_state);
  }
}
