<?php
/**
 * @file
 * Code for the PECE Artifacts - fieldnote module.
 */

include_once 'pece_artifacts_fieldnote.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_artifacts_fieldnote_form_pece_artifact_fieldnote_node_form_alter(&$form, &$form_state) {
  $node = $form['#node'];

  // Title isn't used in field note contents so it can be omitted from the form.
  $form['title']['#required'] = FALSE;
  $form['title']['#default_value'] = 'pece_artifact_fieldnote_' . $node->created;
  $form['title']['#attributes']['class'][] = 'element-invisible';

  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
  // We cannot allow the content to be authored by anonymous.
  $form['author']['name']['#required'] = TRUE;

  if (module_exists('pece_profile')) {
    array_unshift($form['#validate'], 'pece_profile_check_author');
  }
}