<?php
/**
 * @file
 * Code for the pece_essay feature.
 */

include_once 'pece_essay.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function pece_essay_ctools_plugin_directory($module, $plugin) {
  if ($module === 'ctools' && $plugin === 'content_types') {
    return 'plugins/' . $module . '/' . $plugin;
  }
}

/**
 * Implements hook_form_ID_alter().
 */
function pece_essay_form_pece_essay_node_form_alter(&$form, &$form_state) {
  // @TODO: show URI field once API is available.
  $form['field_pece_uri']['#access'] = FALSE;
  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
}

/**
 * Implements hook_panelizer_ipe_access() by pece_panels.
 */
function pece_essay_panelizer_ipe_access($display, $entity_type, $entity) {
  foreach ($entity->panelizer as $view_mode => $panelizer) {
    if ($panelizer->display->storage_id === $display->storage_id) {
      $entity->panelizer_view_mode = $view_mode;
      break;
    }
  }

  return $entity->panelizer_view_mode === 'free_panel' && entity_access('update', $entity_type, $entity);
}

/**
 * Helper function to validate adminsitrator role for current logged user.
 */
function _pece_essay_is_administrator() {
  global $user;
  $admin_role = user_role_load_by_name('administrator');
  if ($user->uid == 1) return TRUE;
  if (user_has_role($admin_role->rid, $user)) return TRUE;

  return FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_essay_form_ctools_node_title_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if (!_pece_essay_is_administrator()) {
    _pece_essay_override_essay_board_title_config_form($form, $form_state, $form_id);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_essay_form_ctools_entity_field_content_type_formatter_options_alter(&$form, &$form_state, $form_id) {
  if (!_pece_essay_is_administrator()) {
    _pece_essay_override_essay_board_contributors_config_form($form, $form_state, $form_id);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_essay_form_ctools_entity_field_content_type_formatter_styles_alter(&$form, &$form_state, $form_id) {
  if (!_pece_essay_is_administrator()) {
    _pece_essay_override_essay_board_contributors_config_styles_form($form, $form_state, $form_id);
  }
}

/**
 * Helper function to override title pane config form for panelizer's
 * free_panel display on PECE Essay board.
 */
function _pece_essay_override_essay_board_title_config_form(&$form, &$form_state, $form_id) {
  if ($form_id != 'ctools_node_title_content_type_edit_form' &&
      strpos(current_path(), 'free_panel') !== FALSE)
    return;

  if (!empty($form['override_title']) && !empty($form['markup'])) {
    $form['override_title']['#default_value'] = 1;
    $form['markup']['#default_value'] = 'h1';
    $form['link']['#default_value'] = FALSE;
  }
}

/**
 * Helper function to set default value and override contributors pane formatter
 * config form for panelizer's free_panel display on PECE Essay board.
 */
function _pece_essay_override_essay_board_contributors_config_form(&$form, &$form_state, $form_id) {
  if ($form_id != 'ctools_entity_field_content_type_formatter_options' &&
    strpos(current_path(), 'free_panel') !== FALSE)
    return;

  // Prevent user to change the default values for this pane.
  $form['override_title']['#disabled'] = 'disabled';
  $form['override_title_text']['#disabled'] = 'disabled';
  $form['override_title_heading']['#disabled'] = 'disabled';
  $form['label']['#disabled'] = 'disabled';
  $form['formatter']['#disabled'] = 'disabled';

  $form['override_title']['#type'] = 'hidden';
  $form['override_title_text']['#type'] = 'hidden';
  $form['override_title_heading']['#type'] = 'hidden';
  $form['label']['#type'] = 'hidden';
  $form['formatter']['#type'] = 'hidden';

  if (!empty($form['formatter'])) {
    $form['formatter']['#default_value'] = 'og_list_default';
  }
}

/**
 * Helper function to override contributors pane styles config form for
 * panelizer's free_panel display on PECE Essay board.
 */
function _pece_essay_override_essay_board_contributors_config_styles_form(&$form, &$form_state, $form_id) {
  if ($form_id != 'ctools_entity_field_content_type_formatter_styles'  &&
    strpos(current_path(), 'free_panel') !== FALSE)
    return;

  // Prevent user to change the default values for this pane.
  $form['delta_offset']['#disabled'] = 'disabled';
  $form['delta_limit']['#disabled'] = 'disabled';
  $form['delta_reversed']['#disabled'] = 'disabled';

  $form['delta_offset']['#type'] = 'hidden';
  $form['delta_limit']['#type'] = 'hidden';
  $form['delta_reversed']['#type'] = 'hidden';
}