<?php
/**
 * @file
 * Code for the pece_essay feature.
 */

include_once 'pece_essay.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function pece_essay_ctools_plugin_directory($module, $plugin) {
  if ($module === 'ctools' && $plugin === 'content_types') {
    return 'plugins/' . $module . '/' . $plugin;
  }
}

/**
 * Implements hook_form_ID_alter().
 */
function pece_essay_form_pece_essay_node_form_alter(&$form, &$form_state) {
  // @TODO: show URI field once API is available.
  $form['field_pece_uri']['#access'] = FALSE;
  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
}

/**
 * Implements hook_panelizer_ipe_access() by pece_panels.
 */
function pece_essay_panelizer_ipe_access($display, $entity_type, $entity) {
  foreach ($entity->panelizer as $view_mode => $panelizer) {
    if ($panelizer->display->storage_id === $display->storage_id) {
      $entity->panelizer_view_mode = $view_mode;
      break;
    }
  }

  return $entity->panelizer_view_mode === 'free_panel' && entity_access('update', $entity_type, $entity);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_essay_form_ctools_node_title_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'pece', 'pece.functions');
  if (!_pece_is_admin()) {
    module_load_include('inc', 'pece_essay', 'pece_essay.functions');
    _pece_essay_override_essay_board_title_config_form($form, $form_state, $form_id);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_essay_form_ctools_entity_field_content_type_formatter_options_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'pece', 'pece.functions');
  if (!_pece_is_admin()) {
    module_load_include('inc', 'pece_essay', 'pece_essay.functions');
    _pece_essay_override_essay_board_contributors_config_form($form, $form_state, $form_id);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_essay_form_ctools_entity_field_content_type_formatter_styles_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'pece', 'pece.functions');
  if (!_pece_is_admin()) {
    module_load_include('inc', 'pece_essay', 'pece_essay.functions');
    _pece_essay_override_essay_board_contributors_config_styles_form($form, $form_state, $form_id);
  }
}

/**
 * Implements hook_pece_annotatable_types_info().
 */
function pece_essay_pece_annotatable_types_info() {
  return array(
    'pece_essay' => 'pece_essay',
  );
}
