<?php
/**
 * @file
 * Code for the PECE Photo Essay feature.
 */

include_once 'pece_photo_essay.features.inc';

/**
 * Implements hook_pece_access_restricted_node_types().
 * Declare pece_photo_essay as a restricted node type.
 */
function pece_photo_essay_pece_access_restricted_node_types() {
  return array(
    'pece_photo_essay' => 'pece_photo_essay',
  );
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 * Add custom fields for the IEF table.
 */
function pece_photo_essay_inline_entity_form_table_fields_alter(&$fields, $context) {
  if ($context['entity_type'] == 'pece_photo_essay_item') {
    $fields['image_artifact_title'] = array(
      'type' => 'callback',
      'label' => t('Artifact'),
      'sanitized' => TRUE,
      'render_callback' => 'pece_photo_essay_ief_image_artifact_title',
      'weight' => 1,
     );

    $fields['image_artifact_image'] = array(
      'type' => 'callback',
      'label' => t('Image'),
      'sanitized' => TRUE,
      'render_callback' => 'pece_photo_essay_ief_image_artifact_image',
      'weight' => 2,
     );
  }
}

/**
 * Custom IEF column content callback.
 */
function pece_photo_essay_ief_image_artifact_title($entity_type, $entity) {
  $item = entity_metadata_wrapper($entity_type, $entity);
  $artifact = $item->field_image_artifact->value();

  return empty($artifact) ? t('Unavailable') : l($artifact->title, 'node/' . $artifact->nid, array(
    'attributes' => array('target' => '_blank'),
  ));
}

/**
 * Custom IEF column content callback.
 */
function pece_photo_essay_ief_image_artifact_image($entity_type, $entity) {
  $item = entity_metadata_wrapper($entity_type, $entity);
  $artifact = $item->field_image_artifact->value();

  return empty($artifact) ? t('Unavailable') : field_view_field('node', $artifact, 'field_pece_media_image', 'mini_teaser');
}
