<?php

/**
 * @file
 * Contains pece_home.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function pece_home_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pece_home module.
    case 'help.page.pece_home':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide custom functionalities for PECE front page.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pece_home_theme() {
  return [
    'pece_home' => [
      'render element' => 'children',
    ],
  ];
}
