<template>
  <div class="about mt-6">
    <h1 class="font-bold text-4xl uppercase mb-6">
      {{ $t('about') }}
    </h1>
    <section>
      <tabs :uppercase="true">
        <tab label="Projects">
          <list-cards :data="simpleCardData" :vertical="true">
            <template v-slot="{ item }">
              <horizontal-card :data="item" />
            </template>
          </list-cards>
        </tab>
        <tab :label="$t('people')">
          <list-cards :data="simpleCardData" :vertical="true">
            <template v-slot="{ item }">
              <horizontal-card :data="item" />
            </template>
          </list-cards>
        </tab>
        <tab label="substantive logics">
          <list-cards :data="simpleCardData" :vertical="true">
            <template v-slot="{ item }">
              <horizontal-card :data="item" />
            </template>
          </list-cards>
        </tab>
        <tab label="design logics">
          <list-cards :data="simpleCardData" :vertical="true">
            <template v-slot="{ item }">
              <horizontal-card :data="item" />
            </template>
          </list-cards>
        </tab>
        <tab :label="$t('about')" class="about__content">
          <p>
            The <strong>Platform for Experimental, Collaborative Ethnography</strong> (<abbr title="Platform for Experimental, Collaborative Ethnography">PECE</abbr>: pronounced “peace”) is an open source (Drupal-based) digital platform that supports multi-sited, cross-scale ethnographic and historical research. The platform links researchers in new ways, enables new kinds of analyses and data visualization, and activates researchers’ engagement with public problems and diverse audiences. PECE is at the center of a research project that explores how digital infrastructure can be designed to support collaborative hermeneutics.
            PECE provides a place to archive and share primary data generated by scholars in the empirical humanities and social sciences, facilitates analytic collaboration, and encourages experimentation with diverse modes of publication. It encourages users to experiment with digitally-mediated interdisciplinary collaboration, provides opportunities to involve students in humanities research as it progresses, and quickens the public availability of humanities research in an open access form. PECE also enables experimentation with new forms of peer review for humanities research, and functions as a portal to a suite of open source tools useful for humanities research, including tools developed in data science for other scientific communities.
          </p>
          <h2>
            GENEALOGY
          </h2>
          <p>
            The PECE project extends from work in cultural anthropology over the last few decades that foregrounds how cultural critique, innovation, and change emerge, and the significance of the genre forms through which culture is expressed (Marcus and Fischer 1986; Clifford and Marcus 1986). This thread of work in cultural anthropology has drawn on literary and language theory to address the significance of genre forms both in everyday enactment of culture in different settings, and in scholarly representations of culture. PECE extends this thread of work into the digital domain through a platform design that reflects critical insight from theories of language, literature, and ethnography, built out organically with original ethnographic material. Thus, while designed to reflect critical theory, PECE is also ethnographically grounded, collaborative in nature, and expressly experimental: the platform is designed to permit change as called for by evolving ethnographic engagements. This entwined development process has been challenging but has proven robust, allowing us to identify needs and explore computational possibilities from within humanities work, learning about and building the kinds of tools that are critical when ethnographers work collaboratively, especially on complex topics involving multiple sites, scales, and actors, and many different kinds of “data”.
          </p>
          <p>
            We developed PECE aware of long-standing effort, often experimental in tenor, to integrate new technologies and media into the work and expression of cultural analysis. Gregory Bateson and Margaret Mead’s stunning work with photography, as both a research tool and means of conveying their analysis, is exemplary in this regard (Bateson and Mead 1942; Jacknis 1988). The history of filmmaking in the conduct and expression of cultural analysis has also laid important ground, generating impressive methodological debates and innovation, and a body of work that literally provides different angles on matters of interest and concern to cultural analysts. Digital tools and modes of presentation add still other possibilities for getting at and sharing understanding of how “culture” works, in historical, geographic, political, economic, and media contexts, always in need of deeper or alternative ways of understanding. The goal of PECE could therefore be described as kaleidoscopic, enriching cultural analysis through use of an ever-evolving array of techniques and technologies – which, together, multiply perspective, give texture to insight, and animate reflexivity.
          </p>
          <h2>
            PECE DESIGN LOGICS
          </h2>
          <p>
            Design of the PECE platform has been oriented by “design logics” that translate critical theoretical commitments drawn from cultural, social, and language theories into digital terms (Fortun et al, forthcoming). One PECE design logic is drawn from Derridean historian of biology Hans-Jörg Rheinberger's conception of how experimental systems work in the sciences, as a play between limits and openness (Rheinberger 1998); another is drawn from James Clifford’s’ writing about how juxtaposition works in both surrealist art and ethnography (Clifford 1981); yet another is drawn from Gregory Bateson's description of what happens when different scales or orders of communication are crossed, resulting in double binds that sometimes produce pathology, sometimes creativity (Bateson 2000 [1956]). These design logics travel with all instances of PECE, built-in and also expressed (see adjacent tab for a detailed articulation of PECE’s “Design Logics”). Such expression lays ground, we hope, both for work with PECE on its own terms, and for contrasting, alternative platform designs.
            The constantly evolving needs of various instances of PECE such as The Asthma Files (a collaborative research project (on worsening asthma incidence and air quality globally) focused with shared questions linking project participants) and the Disaster-STS Research Network (an international network connecting researchers around the world studying how disasters of different types, in different regions of the world, are anticipated and managed) also orient the design of the platform.
          </p>
          <h2>
            PECE SUBSTANTIVE LOGICS
          </h2>
          <p>
            The development of PECE has also been motivated by an array of concerns that we have come to refer as “substantive logics.” Substantive logics are reasons–theoretical, practical, and political–for investing in a given project. These logics often multiply as a project matures, and different collaborators bring different logics to a project. Substantive logics for PECE, for example, include the complex, pluralized knowledge demands of environmental health, but also the need for infrastructure supporting open sharing of research data, as now required by many journals and funders (the European Union and the US National Science Foundation, for example). New expectations for “open science” have technical requirements, while also calling out questions about how researchers should relate to each other, to those they study and work with, to their funders (often taxpayers), and to society writ large (at a moment that many consider to be a time of ecological, intellectual, and political crisis). The need for projects that work out the latter–what can be called the social contract of contemporary research–is another of PECE’s substantive logics.
          </p>
          <p>
            Articulations that further detail PECE’s intellectual genealogies and interventions can be found here.
          </p>
          <h2>
            PECE AS RESEARCH INFRASTRUCTURE
          </h2>
          <p>
            PECE is thus an intensively customized, open source content management system that has been built to address the global challenge of creating research infrastructure to support deeply interdisciplinary and international research that addresses complex problems such as global environmental health and disaster prevention, response, and recovery. Such problems have dimensions that require the integration of data and analysis from the humanities, social and natural sciences, and engineering, and thus will require robust digital infrastructure for humanities researchers, designed to be interoperable with research infrastructure developed for other fields.
          </p>
          <p>
            We think of PECE as a triptych, with space for archiving, analysis, and crafted expression of ethnographic insight. Importantly, the middle space – for collaborative analysis – is where we’ve focused and invested most: here, especially, is where “collaborative hermeneutics” is being worked out. PECE’s design group has now developed and tested multiple digital functions that enable ethnographic collaboration. In the next phase of the project, we will refine existing functions and develop others, through side-by-side development of diverse ethnographic projects on separate platforms. To ensure such interoperability, we have also worked closely with data scientists (at Rensselaer Polytechnic Institute), and within the Research Data Alliance (RDA), an international initiative to enhance capacity to archive, preserve, analyze, and share data within and across research communities.
          </p>
          <p>
            PECE was built and is governed by a group of interdisciplinary scholars at University of California Irvine, Rensselaer Polytechnic Institute, Indian Institute of Technology Hyderabad, and Steven’s Institute of Technology. It is currently hosted at University of California Irvine. It can be freely downloaded at GitHub and installed locally to support different kinds of projects.
          </p>
          <h2>
            REFERENCES:
          </h2>
          <ul>
            <li>
              Bateson, Gregory. 2000 [1956]. “Toward a Theory of Schizophrenia.” Steps to an Ecology of Mind. Chicago, IL: University of Chicago Press. pp 201-227.
            </li>
            <li>
              Bateson, Gregory and Margaret Mead. 1942. Balinese Character: A Photographic Analysis. New York, NY: Academy of Sciences.
            </li>
            <li>
              Clifford, James. 1981. “On Ethnographic Surrealism.” Comparative Studies in Society and History 23 (4): 539-564.
            </li>
            <li>
              Clifford, James and George Marcus. 1986. Writing Culture: The Poetics and Politics of Ethnography. Berkeley, CA: University of California Press.
            </li>
            <li>
              Fortun, Kim, Brian Callahan, Brandon Costelloe-Kuehn, Brad Fidler, Alison Kenner, Aalok Khandekar, Alli Morgan, Lindsay Poirier, and Mike Fortun. Forthcoming. “Hosting the Platform for Experimental, Collaborative Ethnography.”
            </li>
            <li>
              Jacknis, Ira. 1988. “Telling a Story about the Past: Fact and Fiction in Two Recent Films about the History of Anthropology.” American Anthropologist 100 (2): 502-509.
            </li>
            <li>
              Marcus, George and Michael M.J. Fischer. 1986. Anthropology as Cultural Critique: An Experimental Moment in the Human Sciences. Chicago, IL: University of Chicago Press.
            </li>
            <li>
              Rheinberger, Hans-Jörg. 1998. “Experimental Systems, Graphematic Spaces.” in Inscribing Science: Scientific Texts and the Materiality of Communication. ed. Lenoir, Timothy. Palo Alto, CA: Stanford University Press.
            </li>
          </ul>
        </tab>
      </tabs>
    </section>
  </div>
</template>

<script>
import { simpleCardData } from '@/utils/fake'

export default {
  name: 'About',
  components: {
    Tabs: () => import(/* webpackChunkName: "tabs" */ '@/components/tabs/Tabs'),
    Tab: () => import(/* webpackChunkName: "tab" */ '@/components/tabs/Tab'),
    ListCards: () => import(/* webpackChunkName: "ListCards" */ '@/components/ListCards'),
    HorizontalCard: () => import(/* webpackChunkName: "HorizontalCard" */ '@/components/cards/HorizontalCard')
  },
  setup () {
    return {
      simpleCardData
    }
  }
}
</script>

<style lang="scss">
.about {
  &__content {
    p {
      @apply mb-3;
    }
    h2 {
      @apply font-bold text-lg mb-3 mt-8;
    }
    ul {
      @apply list-disc ml-5;
      li {
        @apply mb-2;
      }
    }
  }
}
</style>
