<?php

/**
* @file
* Code for PECE - Notifications.
*/

include_once 'pece_notifications.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_notifications_form_user_register_form_alter(&$form, &$form_state) {
  $form['account']['notify']['#default_value'] = 1;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_notifications_form_user_cancel_confirm_form_alter(&$form, &$form_state) {
  $form['user_cancel_notify']['#default_value'] = 1;
}
