<?php
// Plugin definition
$plugin = array(
  'title' => t('Douby Double'),
  'icon' => 'pece-douby-double.png',
  'category' => t('PECE'),
  'theme' => 'pece_douby_double',
  'regions' => array(
    'sidebartop' => t('Sidebar Top'),
    'sidebarbottom' => t('Sidebar Bottom'),
    'contentheader' => t('Content Header'),
    'contenttop' => t('Content Top'),
    'contentbottom' => t('Content Bottom'),
    'contentfooter' => t('Content Footer'),
  ),
);
