<?php
/**
 * @file
 * Code for the pece_artifacts_pdf feature.
 */

include_once 'pece_artifacts_pdf.features.inc';

/**
 * Implements hook_modules_enabled().
 *
 * This hook is implemented to assign some default permissions for PECE's PDF
 * Document artifacts.
 * This has to be done in this hook to run after both features
 * and defaultconfig which power the functionality. Hopefully a more general
 * solution can be found. More information - http://drupal.org/node/1837312.
 */
function pece_artifacts_pdf_modules_enabled($modules) {

  // Only run this logic if we are executing as part of an install profile
  // and only for this particular module.
  if (drupal_installation_attempted() && in_array('pece_artifacts_pdf', $modules)) {

    $perms = array(
      'create pece_artifact_pdf content',
      'delete own pece_artifact_pdf content',
      'edit own pece_artifact_pdf content',
    );

    foreach ($perms as $perm) {
      // Define some permissions for the authentcated user role
      user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array($perm));
    }
  }
}
