<?php
/**
 * @file
 * Contains \Drupal\pece_migrate\Plugin\migrate\source\Node.
 */
namespace  Drupal\pece_migrate\Plugin\migrate\source;
use Drupal\migrate\Row;
use Drupal\node\Plugin\migrate\source\d7\NodeComplete as D7Node;

/**
 * Gets all node revisions from the source, including translation revisions.
 *
 * @MigrateSource(
 *   id = "v1_node",
 *   source_module = "node"
 * )
 */
class Node extends D7Node {

  public function query() {
    $query =  parent::query(); // TODO: Change the autogenerated stub

    $query->leftJoin('field_data_group_content_access', 'og', '[nr].[vid] = [og].[revision_id]');
//    $query->fields('og', [
//      'entity_id',
//    ]);
    $query->addField('og', 'entity_id', 'og_entity_id');
    return $query;
  }

  /**
   * {@inheritdoc}
   */
  public function fields() {
    $fields = parent::fields() + ['alias' => $this->t('Path alias')];
    $fields += ['permission_by_group_view' => $this->t('Permissão para grupos')];
    return $fields;
  }

  /**
   * {@inheritdoc}
   */
  public function prepareRow(Row $row) {
    // Include path alias.
    $nid = $row->getSourceProperty('nid');
    $query = $this->select('url_alias', 'ua')
      ->fields('ua', ['alias']);
    $query->condition('ua.source', 'node/' . $nid);
    $alias = $query->execute()->fetchField();
    if (!empty($alias)) {
      $row->setSourceProperty('alias', '/' . $alias);
    }

    $row->setSourceProperty('permission_by_group_view', $row->getSourceProperty('og_entity_id'));
    return parent::prepareRow($row);
  }
}
