<?php

namespace Drupal\pece_migrate\Plugin\migrate\source;

use Drupal\migrate\Row;
use Drupal\user\Plugin\migrate\source\d7\User as D7User;

/**
 * Gets all users from the source.
 *
 * @MigrateSource(
 *   id = "v1_user_source",
 *   source_module = "user"
 * )
 */
class User extends D7User {

  const ROLE_RESEARCHER = 'researcher';
  const ROLE_CONTRIBUTOR = 'contributor';

  protected $permissionByUserView = [];

  /**
   *
   */
  public function query() {
    // @todo Change the autogenerated stub.
    $query = parent::query();

    return $query;
  }

  /**
   * {@inheritdoc}
   */
  public function fields() {
    $fields = parent::fields() + ['alias' => $this->t('Path alias')];
    $fields += ['d7_merged_roles' => $this->t('Merged roles')];
    return $fields;
  }

  /**
   * {@inheritdoc}
   *
   * @throws \Exception
   */
  public function prepareRow(Row $row) {
    $uid = $row->getSourceProperty('uid');

    $roles = $this->select('users_roles', 'ur')
      ->fields('ur', ['rid'])
      ->condition('ur.uid', $uid)
      ->execute()
      ->fetchCol();

    $rolesByNewName = array_map([$this, 'callbackRidToName'], $roles);
    $roles = array_unique($rolesByNewName);
    $row->setSourceProperty('d7_merged_roles', $roles);

    return parent::prepareRow($row);
  }

  /**
   *
   */
  public function callbackRidToName($id) {
    $roleMap = [
    // Administrator.
      3 => "administrator",
    // Editor.
      4 => "contributor",
    // Contributor.
      5 => "contributor",
    // Researcher.
      6 => "contributor",
    // Data Importer.
      8 => "data_manager",
    // Platform Director.
      9 => "platform_manager",
    // Manager.
      10 => "platform_manager",
    ];

    return $roleMap[$id];
  }

}
