<?php

/**
 * @file
 * Contains pece_essays.module.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pece_essays_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pece_essays module.
    case 'help.page.pece_essays':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide common functionalities among Essays') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter() for the pece essay edit form.
 *
 * We will *always* hide the legacy HTML toggle on the add form.
 */
function pece_essays_form_node_pece_essay_edit_form_alter(&$form, $form_state, $form_id) {
  // Feature save and edit layout button; move Save button into kebab menu.
  // Except none of this does anything because Gin is bloody ridiculous.

  $form['actions']['submit']['#button_type'] = 'secondary';
  $form['actions']['layout_builder_save_and_edit_layout']['#button_type'] = 'primary';
  $form['actions']['layout_builder_save_and_edit_layout']['#gin_action_item'] = TRUE;

  $node = $form_state->getFormObject()->getEntity();
  if (!$node->field_legacy_rendered_html->value) {
    unset($form['field_override_legacy_with_new']);
  }
}

/**
 * Implements hook_form_alter() for the pece essay form (meaning add/create).
 *
 * On the condition form, we only hide the legacy HTML toggle conditionally.
 */
function pece_essays_form_node_pece_essay_form_alter(&$form, $form_state, $form_id) {
  unset($form['field_override_legacy_with_new']);
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function pece_essays_entity_view_mode_alter(&$view_mode, $context) {
  $enabled_displays = [];
  $load_ids = [];
  $entity_type = $context->getEntityType();
  $config_prefix = 'core.entity_view_display';
  $entity_type_id = $entity_type->id();
  $ids = \Drupal::configFactory()->listAll($config_prefix . '.' . $entity_type_id . '.' . $context->bundle() . '.');
  foreach ($ids as $id) {
    $config_id = str_replace($config_prefix . '.', '', $id);
    [,, $display_mode] = explode('.', $config_id);
    if ($display_mode != 'default') {
      $load_ids[] = $config_id;
    }
  }
  $displays = \Drupal::service('entity_type.manager')->getStorage('entity_view_display')->loadMultiple($load_ids);
  foreach ($displays as $display) {
    if ($display->status()) {
      $enabled_displays[] = $display->get('mode');
    }
  }

  if ($view_mode !== 'full' && !in_array($view_mode, $enabled_displays)) {
    $view_mode = 'card';
  }
}
