<?php
/**
 * @file
 * Code for the Groups feature.
 */

include_once 'pece_groups.features.inc';


/**
 * Implements hook_menu().
 */
function pece_groups_menu() {
  $items['node/%node/group'] = array(
    'title' => 'Edit Group',
    'page callback' => 'pece_groups_edit_group_field',
    'page arguments' => array(1),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'pece_groups.pages.inc',
  );

  return $items;
}


/**
 * Implements hook_field_access().
 */
function pece_groups_field_access($op, $field, $entity_type, $entity, $account) {
  $hide_fields = array(
    'title',
    'body',
    'field_pece_uri',
    'field_pece_contributors',
    'field_pece_crit_commentary',
    'field_pece_artifacts',
    'field_pece_media_image',
    'field_pece_media_pdf',
    'field_pece_website_url',
    'field_pece_media_video',
    'field_pece_iframe',
    'field_pece_file_format',
    'field_pece_media_duration',
    'field_pece_source',
    'field_pece_language',
    'field_pece_fieldsite',
    'field_pece_use_fieldsite_local',
    'group_content_access',
    'field_pece_location',
    'field_pece_license',
    'field_permissions',
    'field_pece_bibliography',
    'field_pece_authors',
    'field_pece_tags',
    'options1', // Publishing Options
  );
  dsm($account);
  if ($op == 'edit' && !empty($entity) && in_array($field['field_name'], $hide_fields)) {
    return FALSE;
  }
}
