<?php
/**
 * @file
 * Code for the Groups feature.
 */

include_once 'pece_groups.features.inc';


/**
 * Implements hook_menu().
 */
function pece_groups_menu() {
  $items['node/%node/edit-group'] = array(
    'title' => 'Edit group audience',
    'page callback' => 'pece_groups_edit_group_field',
    'page arguments' => array(1),
    'access callback' => 'pece_groups_edit_group_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  return $items;
}

/**
 *  Access Callback.
 */
function pece_groups_edit_group_access($node) {
  $skip_content = array(
    'pece_group',
    'pece_memo',
    'pece_essay',
    'pece_photo_essay',
  );
  return (in_array($node->type, $skip_content)) ? FALSE : user_is_logged_in();
}

/**
 * Menu callback; Presents the group audiece field editing form given a node.
 */
function pece_groups_edit_group_field($node) {
  drupal_set_title(t('<em>Edit</em> @title', array(
    '@title' => check_plain($node->title)
  )), PASS_THROUGH);

  $form_state['build_info']['args'] = array($node);
  form_load_include($form_state, 'inc', 'node', 'node.pages');

  $form = drupal_build_form($node->type . '_node_form', $form_state);
  _pece_groups_hide_edit_form_fields($form);
  _pece_groups_edit_form_fields_invisible($form);

  return $form;
}

/**
 * Helper for hidding fields (access FALSE) on node edit form.
 */
function _pece_groups_hide_edit_form_fields(&$form, $fields = array()) {
  if (empty($fields)) {
    $fields = array(
      'title',
      'body',
      'options1', // Publishing Options
      'group_access',
      'field_pece_uri',
      'field_pece_tags',
      'field_pece_iframe',
      'field_pece_source',
      'field_permissions',
      'field_pece_license',
      'field_pece_authors',
      'field_pece_location',
      'field_pece_language',
      'field_pece_fieldsite',
      'field_pece_artifacts',
      'og_roles_permissions',
      'group_content_access',
      'field_pece_project_ref',
      'field_pece_file_format',
      'field_pece_website_url',
      'field_pece_bibliography',
      'field_pece_contributors',
      'field_pece_media_duration',
      'field_pece_crit_commentary',
      'field_pece_photo_essay_items',
      'field_pece_substantive_logic',
      'field_pece_use_fieldsite_local',
    );
  }
  foreach ($fields as $field) {
    $form[$field]['#access'] = FALSE;
  }
}

/**
 * Helper for hidding by adding 'element-invisible' class on edit form fields.
 */
function _pece_groups_edit_form_fields_invisible(&$form, $fields = array()) {
  if (empty($fields)) {
    $fields = array(
      'field_thumbnail',
      'field_pece_media_pdf',
      'field_pece_media_image',
      'field_pece_media_audio',
      'field_pece_media_video',
    );
  }
  foreach ($fields as $field) {
    $form[$field]['#attributes']['class'][] = 'element-invisible';
  }
}
