<?php
/**
 * @file
 * Drupal Ipsum installation hooks.
 */

/**
 * Implements hook_install().
 */
function drupal_ipsum_install() {
  // Enable Drupal Ipsum by default on the "Article" and "Basic Page"content types.
  variable_set("drupal_ipsum_article_enable", TRUE);
  variable_set("drupal_ipsum_page_enable", TRUE);
}

/**
 * Implements hook_uninstall().
 */
function drupal_ipsum_uninstall() {
  // Remove Drupal Ipsum variables.
  $result = db_query("SELECT name FROM {variable} WHERE name LIKE 'drupal_ipsum%'");

  foreach ($result as $row) {
    variable_del($row->name);
  }
}