<?php
/**
 * @file
 * Code for the PECE Annotations feature.
 */

include_once 'pece_annotations.features.inc';

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function pece_annotations_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_menu().
 */
function pece_annotations_menu() {

 $items['annotation/add/%ctools_js/%node/form'] = array(
    'title' => 'Annotate',
    'page callback' => 'pece_annotations_annotate_form',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_annotations_form_pece_annotation_node_form_alter(&$form, &$form_state) {
  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
  // We cannot allow the content to be authored by anonymous.
  $form['author']['name']['#required'] = TRUE;
}

/**
 * Implements hook_field_extra_fields().
 */
function pece_annotations_field_extra_fields() {
  $extra['node']['pece_annotation']['display']['card'] = array(
    'label' => t('Structured analytic (Question set)'),
    'weight' => 1,
  );
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function pece_annotations_node_view($node, $view_mode, $langcode) {

  if ($view_mode !== 'card') {
    return;
  }
  $node->content['field_pece_struct_analytics'] = array();
  $node->content['field_pece_struct_analytics']['#weight'] = 100;
  $node->content['field_pece_struct_analytics']['#prefix'] = '<div class="pece-struct-analytic-wrapper">';
  $node->content['field_pece_struct_analytics']['#suffix'] = '</div>';
  $node_wrapper = entity_metadata_wrapper('node', $node);
  $question_set = $node_wrapper->field_pece_analytic->field_pece_struct_analytics->value();
  foreach ($question_set as $key => $term) {
    $term_view = taxonomy_term_view($term, 'meta-content');
    $node->content['field_pece_struct_analytics'][] = $term_view;
  }
}

/**
 * Page callback: Handles multistep precessing.
 *
 * @return string
 *   Multistep wizard output.
 *
 * @see pece_annotations_annotate_menu()
 */
function pece_annotations_annotate_form($js = NULL, $node = NULL, $step = NULL) {

  if ($js) {
    ctools_include('modal');
    ctools_include('ajax');
  }

  if (!$node) {
    $form['empty'] = array(
      '#markup' => 'Missing artifact data. Please check the link url.'
    );

    return drupal_render($form);
  }

  $path_pattern = "annotation/add/" . ($js ? 'ajax' : 'nojs') . "/" . $node->nid . "/form";

  // Define array for ctools multistep wizard.
  $form_info = array(
    'id' => 'pece_annotations_annotate',
    'path' => $path_pattern . '/%step',
    'show trail' => TRUE,
    'show back' => TRUE,
    'show cancel' => TRUE,
    'show return' => FALSE,
    'next callback' =>  'pece_annotations_annotate_wizard_next',
    'finish callback' => 'pece_annotations_annotate_wizard_finish',
    'cancel callback' => 'pece_annotations_annotate_wizard_cancel',
    'return path' => $path_pattern,

   // Forms order.
    'order' => array(
      'start' => t('Question set selection'),
      'second' => t('Question selection'),
      'third' => t('Annotate'),
    ),

   // Define forms
    'forms' => array(
      'start' => array(
        'form id' => 'pece_annotations_annotate_form_start'
      ),
      'second' => array(
        'form id' => 'pece_annotations_annotate_form_second'
      ),
      'third' => array(
        'form id' => 'pece_annotations_annotate_form_third',
      ),
    ),
  );

  // We're not using any real storage here, so we're going to set our
  // object_id to 1. When using wizard forms, id management turns
  // out to be one of the hardest parts. Editing an object with an id
  // is easy, but new objects don't usually have ids until somewhere
  // in creation.
  //
  // We skip all this here by just using an id of 1.
  $object_id = 1;

  if (empty($step)) {

    // We reset the form when $step is NULL because that means they have
    // for whatever reason started over.
    pece_annotations_annotate_cache_clear($object_id);
    $step = 'start';
  }

  // This automatically gets defaults if there wasn't anything saved.
  $object = pece_annotations_annotate_cache_get($object_id);

  // live $form_state changes.
  $form_state = array(
    'ajax' => $js,
    // Put our object and ID into the form state cache so we can easily find it.
    'object_id' => $object_id,
    'object' => &$object,
  );

  // Stores the node entity to use later.
  $form_state['object']->artifact = $node;


  // Send this all off to our form. This is like drupal_get_form only wizardy.
  ctools_include('wizard');
  $form = ctools_wizard_multistep_form($form_info, $step, $form_state);
  $output = drupal_render($form);

  if ($js) {
    // If javascript is active, we have to use a render array.
    $commands = array();
    if ($output === FALSE || !empty($form_state['complete'])) {
      // Dismiss the modal.
      $commands[] = ajax_command_html('#ctools-sample', render(pece_annotations_annotate_get_result($object)));
      $commands[] = ctools_modal_command_dismiss();
    }
    elseif (!empty($form_state['cancel'])) {

      // If cancelling, return to the activity.
      $commands[] = ctools_modal_command_dismiss();
    }
    else {
      $commands = ctools_modal_form_render($form_state, $output);
    }
    print ajax_render($commands);
  }
  else {
    if ($output === FALSE || !empty($form_state['complete'])) {
      return drupal_goto('node/' . $object->nid);
    }
    elseif (!empty($form_state['cancel'])) {
      drupal_goto('node/' . $node->nid);
    }
    else {
      return $output;
    }
  }
}

/**
 * Implements hook_form_pece_annotations_annotate_form_alter().
 *
 * Add a Save & Continue button, to keep adding annotations.
 * Done in a form alter so that CTools default processors for buttons might step in.
 * It wouldn't work if done after ctools_wizard_multistep_form call.
 */
function pece_annotations_form_pece_annotations_annotate_form_third_alter(&$form, &$form_state, $form_id) {
  $form['buttons']['save_continue'] = array(
    '#type' => 'submit',
    '#value' => t('Save & Continue'),
    '#wizard type' => 'next',
    '#next' => 'start',
    '#attributes' => array('class' => array('ctools-use-ajax')),
  );
}

/**
 * Clears the wizard cache.
 *
 * @param integer $id
 *   cache id.
 */
function pece_annotations_annotate_cache_clear($id) {
  ctools_include('object-cache');
  ctools_object_cache_clear('pece_annotations_annotate', $id);
}

/**
 * Stores our little cache so that we can retain data from form to form.
 *
 * @param integer $id
 *   cache id.
 * @param object $object
 *   object with form values.
 */
function pece_annotations_annotate_cache_set($id, $object) {
  ctools_include('object-cache');
  ctools_object_cache_set('pece_annotations_annotate', $id, $object);
}

/**
 * Gets the current object from the cache, or default.
 *
 * @param integer $id
 *   cache id.
 *
 * @return object
 *   cache with stored stuff.
 */
function pece_annotations_annotate_cache_get($id) {
  ctools_include('object-cache');
  $object = ctools_object_cache_get('pece_annotations_annotate', $id);
  if (!$object) {
    // Create a default object.
    $object = new stdClass;
  }

  return $object;
}

/**
 * Handles the 'next' click on the form wizard.
 *
 * All we need to do is store the updated pane in the cache.
 */
function pece_annotations_annotate_wizard_next(&$form_state) {
  pece_annotations_annotate_cache_set($form_state['object_id'], $form_state['object']);
}

/**
 * Handles the 'finish' click on the form wizard.
 *
 * All we need to do is set a flag so the return can handle adding
 * the pane.
 */
function pece_annotations_annotate_wizard_finish(&$form_state) {
  $form_state['complete'] = TRUE;
}

/**
 * Handles the 'cancel' click on the form wizard.
 */
function pece_annotations_annotate_wizard_cancel(&$form_state) {
  $form_state['cancel'] = TRUE;
}


function _form_header(&$form, &$form_state) {

  $steps = array();
  $steps = array_keys($form_state['form_info']['order']);

  $items = array();
  if(isset($form_state['object']->header)) {
    foreach ($steps as $step) {
      $items[$step] = $form_state['object']->header[$step];
      if ($step == $form_state['step']) {
        break;
      }
    }
  }

  $form['annotation_info'] = array(
    '#type' => 'fieldset',
    '#title' => t('Annotation info:'),
    '#weight' => -10,
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form['annotation_info']['data'] = array(
    '#type' => 'item',
    '#markup' => theme('item_list', array('items' => $items)),
  );

  return $form;
}

/**
 * Generates first form.
 *
 * @ingroup forms
 */
function pece_annotations_annotate_form_start($form, &$form_state) {

  $voc = taxonomy_vocabulary_machine_name_load('pece_structured_analytics');
  $tree = taxonomy_get_tree($voc->vid);
  $items = $header = array();

  $form['new_struct_analytics'] = array(
    '#type' => 'textfield',
    '#title' => 'Question set title',
    '#weight' => 100,
    '#states' => array(
      'visible' => array(
        'select[name="struct_analytics"], input[name="struct_analytics"]' => array('value' => 'add_new'),
      ),
    ),
  );

  if (empty($tree)) {
    return $form;
  }

  foreach ($tree as $term) {
    $items[$term->tid] = $term->name ;
  }

  $form_state['object']->struct_analytics_tree = $items;

  $header = '<b>Artifact</b>: ' . $form_state['object']->artifact->title;
  $form_state['object']->header['start'] = $header;

  _form_header($form, $form_state);

  $form['struct_analytics'] = array(
    '#type' => 'radios',
    '#title' => t('Structured analytics'),
    '#description' => t('Select the Question set you are about to respond.'),
    '#options' =>  array('add_new' => '< Create new  >') + $items,
  );

  if (count($items) > 5) {
    $form['struct_analytics']['#type'] = 'select';
    $form['struct_analytics']['#empty_value'] = '';
  }

  return $form;
}


/**
 * Handles validate of first form.
 */
function pece_annotations_annotate_form_start_validate($form, &$form_state) {
  if (empty($form_state['values']['struct_analytics']) && empty($form_state['values']['new_struct_analytics'])) {
    form_set_error('struct_analytics', t('You have to choose at least one of the structured analytics options below or create a new question set by filling the %field field.', array('%field' => $form['new_struct_analytics']['#title'])));
  }

  if ($form_state['values']['struct_analytics'] == 'add_new' && empty($form_state['values']['new_struct_analytics'])) {
    form_set_error('new_struct_analytics', t('Field %field is required.', array('%field' => $form['new_struct_analytics']['#title'])));
  }
}

/**
 * Handles submit of first form.
 */
function pece_annotations_annotate_form_start_submit($form, &$form_state) {
  if (!empty($form_state['values']['struct_analytics'])) {
    $form_state['object']->struct_analytics = $form_state['values']['struct_analytics'];
  }
  if (!empty($form_state['values']['new_struct_analytics'])) {
    $vocabulary = taxonomy_vocabulary_machine_name_load('pece_structured_analytics');

    $term = (object) array(
      'vid' => $vocabulary->vid,
      'name' => $form_state['values']['new_struct_analytics'],
    );

    taxonomy_term_save($term);
    $form_state['object']->struct_analytics = $term->tid;
    $form_state['object']->struct_analytics_tree[$term->tid] = $term->name;
  }
}

/**
 * Generates second form.
 *
 * @ingroup forms
 */
function pece_annotations_annotate_form_second($form, &$form_state) {
  global $user;

  $header = array();
  $struct_analytic_tid = $form_state['object']->struct_analytics;

  $header = '<b>Question set</b>: ' . $form_state['object']->struct_analytics_tree[$struct_analytic_tid];
  $form_state['object']->header['second'] = $header;

  _form_header($form, $form_state);

  $form['new_analytic'] = array(
    '#type' => 'textfield',
    '#title' => 'Question title',
    '#weight' => 100,
    '#states' => array(
      'visible' => array(
        'select[name="analytic"], input[name="analytic"]' => array('value' => 'add_new'),
      ),
    ),
  );

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'pece_analytic')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_pece_struct_analytics', 'target_id', array($struct_analytic_tid))
    ->addMetaData('account', user_load($user->uid));

  $result = $query->execute();

  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    $analytics_items = entity_load('node', $nids);
  }

  $items = array();

  foreach ($analytics_items as $analytic) {
    $items[$analytic->nid] = $analytic->title;
  }
  $form_state['object']->analytics_tree = $items;

  $first = reset($analytics_items);

  $form['analytic'] = array(
    '#type' => 'radios',
    '#title' => t('Analytic'),
    '#description' => t('The Question this annotation responds to.'),
    '#options' =>  array('add_new' => '< Create new  >') + $items,
    '#default_value' => !empty($items) ? $first->nid : 'add_new',
  );

  if (count($items) > 5) {
    $form['analytic']['#type'] = 'select';
    $form['analytic']['#empty_value'] = '';
  }

  return $form;
}


/**
 * Handles validate of first form.
 */
function pece_annotations_annotate_form_second_validate($form, &$form_state) {
  if (empty($form_state['values']['analytic']) && empty($form_state['values']['new_analytic'])) {
    form_set_error('analytic', t('You have to choose at least one of the analytics options below or create a new question by filling the %field field.', array('%field' => $form['new_analytic']['#title'])));
  }

  if ($form_state['values']['analytic'] == 'add_new' && empty($form_state['values']['new_analytic'])) {
    form_set_error('new_analytic', t('Field %field is required.', array('%field' => $form['new_analytic']['#title'])));
  }
}

/**
 * Handles submit for second form.
 */
function pece_annotations_annotate_form_second_submit($form, &$form_state) {
  if (!empty($form_state['values']['analytic'])) {
    $form_state['object']->analytic = $form_state['values']['analytic'];
  }

  if (!empty($form_state['values']['new_analytic'])) {
    global $user;

    $analytic_node_values =  array(
      'type' => 'pece_analytic',
      'title' => $form_state['values']['new_analytic'],
    );

    $analytic_node = entity_create('node', $analytic_node_values);
    $analytic_node->uid = $user->uid;
    $node_wrapper = entity_metadata_wrapper('node', $analytic_node);
    $node_wrapper->field_pece_struct_analytics->set(array($form_state['object']->struct_analytics));
    $node_wrapper->save();
    $form_state['object']->analytic = $analytic_node->nid;
    $form_state['object']->analytics_tree[$analytic_node->nid] = $analytic_node->title;
  }
}

/**
 * Generates third form.
 *
 * @ingroup forms
 */
function pece_annotations_annotate_form_third($form, &$form_state) {
  global $user;

  $header = array();
  $analytic_id = $form_state['object']->analytic;

  $header = '<b>Question:</b> ' . $form_state['object']->analytics_tree[$analytic_id];
  $form_state['object']->header['third'] = $header;

  _form_header($form, $form_state);

  // Create the entity to attach its fields to the form.
  $values = array(
    'type' => 'pece_annotation',
    'uid' => $user->uid,
    'status' => 1,
    'comment' => 0,
    'promote' => 0,
  );
  $entity = $form_state['object']->annotation_entity = entity_create('node', $values);

  $options = array(
    'field_name' => array(
      'field_pece_license',
      'field_pece_tags',
    ),
  );
  field_attach_form('node', $entity, $form, $form_state, NULL, array());

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#required' => TRUE,
    '#weight' => 100,
  );

  $form['body'][LANGUAGE_NONE][0] = array(
    '#title' => t('Annotation'),
    '#rows' => 5,
    '#cols' => 60,
  ) + $form['body'][LANGUAGE_NONE][0];

  // unset unnecessary fields.
  unset($form['field_pece_analytic']);
  unset($form['field_pece_artifact']);
  unset($form['field_pece_uri']);

  return $form;
}

/**
 * Handles submit for third form.
 */
function pece_annotations_annotate_form_third_submit(&$form, &$form_state) {

  $form_state['object']->title = $form_state['values']['title'];
  $form_state['object']->body = $form_state['values']['body'];

  pece_annotations_annotate_form_save_annotation($form, $form_state);

  if ($form_state['clicked_button']['#wizard type'] == 'next') {
    pece_annotations_annotate_form_save_continue($form, $form_state);
  }
  else if ($form_state['ajax']) {
    ctools_include('ajax');
    ctools_add_js('ajax-responder');
    $commands[] = ctools_ajax_command_reload();
    print ajax_render($commands);
    exit;
  }
}

/**
 * Save the annotation created by the wizard form.
 */
function pece_annotations_annotate_form_save_annotation(&$form, &$form_state) {
  global $user;

  $values = array(
    'type' => 'pece_annotation',
    'uid' => $user->uid,
    'status' => 1,
    'comment' => 0,
    'promote' => 0,
  );

  $entity = entity_create('node', $values);
  $form_state['object']->nid = $entity->nid;
  $annotation_values = $form_state['object'];
  $node_wrapper = entity_metadata_wrapper('node', $entity);

  // Manualy add the values into the node.
  $node_wrapper->title->set($annotation_values->title);
  $node_wrapper->body->set(array('value' => $annotation_values->body));
  $node_wrapper->field_pece_uri->set('pece_annotation_' . REQUEST_TIME);
  $node_wrapper->field_pece_artifact->set(intval($annotation_values->artifact->nid));
  $node_wrapper->field_pece_analytic->set(intval($annotation_values->analytic));

  // An easy way to save the license and tags fields.
  field_attach_submit('node', $entity, $form, $form_state);
  $node_wrapper->save();

  drupal_set_message(t('Your annotation was been created. !link ', array(
    '!link' => l('View annotation', 'node/' . $entity->nid),
  )), 'status');
}

/**
 * Save the annotation and return to the beginning of the wizard.
 */
function pece_annotations_annotate_form_save_continue(&$form, &$form_state) {
  $form_state['clicked_button']['#wizard type'] = 'next';
  $form_state['clicked_button']['#next'] = 'second';
}

/**
* Get all annotatable entities.
*/
function pece_annotations_fetch_annotatable_entities() {
  $annotatable = module_invoke_all('pece_annotatable_types_info');
  drupal_alter('pece_annotatable_types_info_alter', $annotatable);
  return $annotatable;
}

/**
 * Implements hook_pece_annotatable_types_info().
 */
function pece_annotations_pece_annotatable_types_info() {
  $annottbl_types = pece_artifacts_fetch_all_types();
  return $annottbl_types;
}
