<?php

/**
 * @file
 * Install, update and uninstall functions for the pece_artifacts_fieldnote module.
 */

/**
 * Rebuild artifact field note default permissions for administrator user role.
 */
function pece_artifacts_fieldnote_update_7001() {
  module_load_include('inc', 'pece', 'pece.functions');
  pece_defaultconfig_component_rebuild_by_name('user_default_permissions', 'pece_artifacts_fieldnote');
}

