<?php
/**
 * @file
 * Code for the PECE Timeline Essay feature.
 */

include_once 'pece_timeline_essay.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function pece_timeline_essay_ctools_plugin_directory($module, $plugin) {
  if ($module === 'ctools' && $plugin === 'content_types') {
    return 'plugins/' . $module . '/' . $plugin;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_timeline_essay_form_pece_timeline_essay_node_form_alter(&$form, &$form_state) {
  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
  // We cannot allow the content to be authored by anonymous.
  $form['author']['name']['#required'] = TRUE;
}

/**
 * Implements hook_panelizer_ipe_access() by pece_panels.
 */
function pece_timeline_essay_panelizer_ipe_access($display, $entity_type, $entity) {
  foreach ($entity->panelizer as $view_mode => $panelizer) {
    if ($panelizer->display->storage_id === $display->storage_id) {
      $entity->panelizer_view_mode = $view_mode;
      break;
    }
  }

  return $entity->panelizer_view_mode === 'free_panel' && entity_access('update', $entity_type, $entity);
}


/**
 * Implements hook_pece_annotatable_types_info().
 */
function pece_timeline_essay_pece_annotatable_types_info() {
  return array(
    'pece_timeline_essay' => 'pece_timeline_essay',
  );
}
