id: global_text_search
theme: peceful
region: header_search
weight: 0
provider: null
plugin: 'configurable_views_filter_block_block:search-page'
settings:
  id: 'configurable_views_filter_block_block:search-page'
  label: ''
  label_display: '0'
  provider: configurable_views_filter_block
  views_label: ''
  visible_filters:
    search_api_fulltext: search_api_fulltext
  no_groups: true
  no_reset: true
  no_sort: false
  no_pager: false
  no_submit: false
visibility: {  }
uuid: 0e818047-3868-4533-9b13-339bf3bd1901
langcode: en
status: false
dependencies:
  config:
    - views.view.search
  module:
    - configurable_views_filter_block
  theme:
    - peceful
