id: bulma_tools
theme: bulma
region: header
weight: 0
provider: null
plugin: 'system_menu_block:tools'
settings:
  id: 'system_menu_block:tools'
  label: Tools
  label_display: visible
  provider: system
  level: 1
  depth: null
  expand_all_items: false
visibility: {  }
uuid: 2cd91a8c-55b7-4887-9b51-5747d3dde5c0
langcode: en
status: false
dependencies:
  config:
    - system.menu.tools
  module:
    - system
  theme:
    - bulma
_core:
  default_config_hash: QJJjJ6HJDvVZazsyjBAOMao6Ffxnior9KqgZxZqPh2E
