_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  auto_entitylabel: -100
  access_policy: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  ark: 0
  asset_injector: 0
  automated_cron: 0
  bef_links_filter: 0
  better_exposed_filters: 0
  bibcite: 0
  bibcite_bibtex: 0
  bibcite_endnote: 0
  bibcite_entity: 0
  bibcite_export: 0
  bibcite_import: 0
  bibcite_marc: 0
  bibcite_migrate: 0
  bibcite_ris: 0
  big_pipe: 0
  bigint: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  blocktabs: 0
  breakpoint: 0
  cer: 0
  cite: 0
  ckeditor5: 0
  ckeditor_media_embed: 0
  color_field: 0
  comment: 0
  components: 0
  conditional_fields: 0
  config: 0
  configurable_views_filter_block: 0
  consumers: 0
  content_moderation: 0
  contextual: 0
  create_referencing_content: 0
  ctools: 0
  dashboards: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  digital_size_formatter: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_form_field_label: 0
  entity_reference_revisions: 0
  epp: 0
  extra_field: 0
  extra_field_configuration: 0
  extra_field_plus: 0
  facets: 0
  facets_exposed_filters: 0
  facets_searchbox_widget: 0
  facets_summary: 0
  fences: 0
  fences_presets: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_resup: 0
  file_resup_media_library: 0
  filter: 0
  forms_steps: 0
  geolocation: 0
  gin_toolbar: 0
  gin_type_tray: 0
  graphql: 0
  graphql_people: 0
  help: 0
  history: 0
  image: 0
  image_replace: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  jquery_ui_tabs: 0
  language: 0
  languagefield: 0
  layout_builder: 0
  layout_builder_component_attributes: 0
  layout_builder_iframe_modal: 0
  layout_builder_operation_link: 0
  layout_builder_restrictions: 0
  layout_builder_save_and_edit: 0
  layout_collapse: 0
  layout_discovery: 0
  layout_library: 0
  layout_options: 0
  layout_paragraphs: 0
  lb_direct_add: 0
  legal: 0
  licenses_vocabulary: 0
  link: 0
  linkit: 0
  location_migration: 0
  media: 0
  media_library: 0
  media_library_edit: 0
  media_library_form_element: 0
  media_migration: 0
  media_migration_tools: 0
  menu_block: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_open_graph: 0
  metatag_verification: 0
  metatag_views: 0
  migmag: 0
  migmag_process: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  nyx_graphql: 0
  nyx_recaptcha: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pbf: 0
  pdf: 0
  pdfpreview: 0
  pece_access: 0
  pece_annotations: 0
  pece_artifacts: 0
  pece_artifacts_audio: 0
  pece_artifacts_bundle: 0
  pece_artifacts_fieldsite: 0
  pece_artifacts_image: 0
  pece_artifacts_pdf: 0
  pece_artifacts_text: 0
  pece_artifacts_video: 0
  pece_artifacts_website: 0
  pece_dashboards: 0
  pece_essay: 0
  pece_essays: 0
  pece_groups: 0
  pece_memo: 0
  pece_migrate: 0
  pece_n8n: 0
  pece_oauth: 0
  pece_photo_essay: 0
  pece_project: 0
  pece_rules_webhook: 0
  pece_subst_logic: 0
  pece_timeline_essay: 0
  phpass: 0
  prepopulate: 0
  profile: 0
  readonly_field_widget: 0
  redirect: 0
  redis: 0
  registration_role: 0
  responsive_image: 0
  rest: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  simple_search_form: 0
  simplify_media_ui: 0
  single_content_sync: 0
  smart_sql_idmap: 0
  smtp: 0
  sophron: 0
  splide: 0
  splide_ui: 0
  svg_image_field: 0
  svg_image_field_media_bundle: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  tomselect: 0
  toolbar: 0
  type_tray: 0
  type_tray_icon_display: 0
  typed_data: 0
  ui_patterns: 0
  ui_patterns_layout_builder: 0
  ui_patterns_layouts: 0
  update: 0
  user: 0
  user_restrictions: 0
  view_mode_page: 0
  views_infinite_scroll: 0
  views_ui: 0
  workflows: 0
  hide_revision_field: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  tvi: 15
  empty_page: 1000
  pece: 1000
theme:
  claro: 0
  gin: 0
  stable9: 0
  bulma: 0
  peceful: 0
profile: pece
