id: node.pece_design_logic.promote
label: 'Promoted to front page'
field_name: promote
entity_type: node
bundle: pece_design_logic
description: ''
required: false
translatable: true
default_value:
  -
    value: 1
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: b341953e-ab57-4459-9ecc-9689858871eb
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_design_logic
