id: node.pece_artifact_pdf.field_authors
label: Creator(s)
field_name: field_authors
entity_type: node
bundle: pece_artifact_pdf
description: 'This field designates the person or people who originally created this artifact.  Creators known to the system will autocomplete; if this does not happen type the full name of a new creator, and it will be added when this artifact is saved. If you do not know the creator of the artifact, type: Unknown'
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      pece_authors: pece_authors
    sort:
      field: name
      direction: asc
    auto_create: true
    auto_create_bundle: ''
field_type: entity_reference
uuid: 9c166d84-6eac-416e-8657-c098990708a7
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_authors
    - node.type.pece_artifact_pdf
    - taxonomy.vocabulary.pece_authors
