name: 'PECE Essay'
type: pece_essay
description: 'A PECE Essay is a collection of artifacts, memos, and essays, organized into a collage, with text added for context.'
help: null
new_revision: true
preview_mode: 0
display_submitted: true
uuid: 96a18294-564c-4e96-a89b-2d30fb86018a
langcode: en
status: true
dependencies:
  module:
    - menu_ui
    - type_tray
third_party_settings:
  type_tray:
    type_category: create
    type_thumbnail: ''
    type_icon: /themes/custom/peceful/icons/icons.svg
    type_description: ''
    existing_nodes_link_text: 'View existing <em class="placeholder">PECE Essay</em> content'
    type_weight: '0'
  menu_ui:
    available_menus: {  }
    parent: ''
_core:
  default_config_hash: vjJUcnavZHrqxjSLYzZcE8EdwskHyy4vlLN9Dy84QUo
