<?php
/**
 * @file
 * Code for the PECE Dashboard feature.
 */

include_once 'pece_dashboard.features.inc';

/**
 * Implements hook_block_info().
 */
function pece_dashboard_block_info() {
  $blocks['dashboard_add_content'] = array(
    'info' => t('Dashboard Add Content'),
  );

  return $blocks;
}

/**
 * Implements hook_url_inbound_alter().
 *
 * Total Control module don't handle well dashboard path for authenticated users
 * without "have total control" permission.
 * Redirects all dashboard sub-path to PECE user's dashboard page.
 */
function pece_dashboard_url_inbound_alter(&$path, $original_path, $path_language) {
  if (module_exists('total_control')) {
    $argument = explode('/', $path);
    if (user_is_logged_in() && isset($argument[0]) && $argument[0] == 'dashboard') {
      $path = 'user/dashboard';
    }
  }
}

/**
 * Implements hook_block_view().
 */
function pece_dashboard_block_view($delta = 'dashboard_add_content') {
  $block['subject'] = t('Add Content');

  $menu_items = node_type_get_types();
  $node_types = array();

  // Remove restricted content types.
  unset($menu_items['panopoly_landing_page']);
  unset($menu_items['panopoly_page']);
  unset($menu_items['pece_about_page']);

  // Hide the following content types from Reasearcher and Contributor users on
  // dashboard's Add Content block.
  $roles = array('researcher', 'contributor');
  $exclude_types = array(
    'biblio',
    'pece_annotation',
    'frontpage_image_slideshow'
  );
  pece_dashboard_hide_content_item_by_role($roles, $exclude_types, $menu_items);

  // Sort items alphabetically.
  asort($menu_items);

  foreach ($menu_items as $menu_item) {
    $link_class = '';

    // We know that's ugly, but this saves us the work of making these names
    // configurable while this is not really necessary for now.
    $node_type = str_replace('_', '-', $menu_item->type);
    $node_title = $menu_item->name;
    $node_title = str_replace(' (Question)', '', $node_title);
    $node_title = str_replace('Artifact - ', '', $node_title);
    $node_title = str_replace('Slideshow Image', 'Frontpage Image Slideshow', $node_title);

    if (strpos($node_type, 'pece-artifact') !== false) {
      $link_class = 'dashboard-artifact-item';
    }

    $node_types[] = array(
      'data' => array(
        '#theme' => 'link',
        '#text' => $node_title,
        '#path' => 'node/add/' . $node_type,
        '#options' => array(
          'attributes' => array(
            'class' => $link_class
          ),
          'html' => TRUE,
        ),
      )
    );
  }

  $block['content'] = array(
    'list' => array(
      '#theme' => 'item_list',
      '#type' => 'ul',
      '#items' => $node_types,
    ),
  );

  return $block = array(
    'subject' => $block['subject'],
    'content' => $block['content'],
  );
}

/**
 * Implements hook_menu().
 */
function pece_dashboard_menu() {
  $items['dashboard'] = array(
    'title' => 'Dashboard',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'user_page',
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'user-menu',
  );

  return $items;
}

function pece_dashboard_hide_content_item_by_role($roles = array(), $exclude = array(), &$node_types = array()) {
  if (empty($roles)) return;
  if (empty($exclude)) return;

  global $user;

  $user_roles = array();
  foreach ($roles as $role_name) {
    $user_roles[] = user_role_load_by_name($role_name);
  }

  foreach ($user_roles as $role) {
    if (in_array($role->rid, array_keys($user->roles))) {
      foreach ($exclude as $type) {
        unset($node_types[$type]);
      }
    }
  }
}
