<?php

/**
 * @file
 * Contains pece_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pece_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pece_migrate module.
    case 'help.page.pece_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate PECE v1 to PECE v2') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function pece_migrate_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'migration_plugins_alter') {
    // Disable media_migration_migration_plugins_alter().
    unset($implementations['media_migration']);
  }
}
