<?php

namespace Drupal\Tests\pece_access\Kernel;

use Drupal\KernelTests\KernelTestBase;
use Drupal\Tests\node\Traits\NodeCreationTrait;
use Drupal\Tests\user\Traits\UserCreationTrait;

/**
 * Test the pece access.
 *
 * @package Drupal\Tests\pece_access\Kernel
 * @group pece_access
 */
class RoleGroupPermissionsTest extends KernelTestBase {

  use NodeCreationTrait;
  use UserCreationTrait;

  /**
   * {@inheritdoc}
   */
  protected $defaultTheme = 'claro';
  protected $profile = 'pece';
  /**
   * The modules to load to run the test.
   *
   * @var array
   */
  public static $modules = [
    'filter',
    'node',
    'pbf',
    'pece_access',
    'system',
    'user',
  ];

  /**
   * {@inheritDoc}
   */
  protected function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub
    $this->installEntitySchema('node');
    $this->installEntitySchema('user');
    $this->installSchema('system', ['sequences']);
    $this->installSchema('node', ['node_access']);
  }

  /**
   * Tests the settings form.
   */
  public function testRoleGroupPermissions() {

    // Create group
    $group = $this->createNode(['type' => 'group']);
    $this->assertIsInt($group);
    // Create researcher in the group
    // Create researcher outside the group
    // Create contributor inside the group
    //Create content
    // Add group permission to this new content only view permission

    // Test researcher outside group can't access
    // Test researcher inside group can access
    // Test contributor can access
    // Test researcher outside group can't edit content
    // Test researcher inside group can't edit content

    // Add role permission to this content with researcher can view and edit

    // Test researcher outside group can't access
    // Test researcher inside group can access
    // Test contributor can't access
    // Test researcher outside group can't edit content
    // Test researcher inside group can edit content
  }
}
