<?php

/**
 * Implements hook_theme().
 */
function pece_annotations_theme() {
  return [
    'node__pece_analytic__analytic_on_annotation_form' => [
      'template' => 'node--pece-analytic--analytic-on-annotation-form',
      'base_hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function pece_annotations_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'entity_browser_analytic_browser_form') {
    $form['#attached']['library'][] = 'pece_annotations/pece_annotations_analytic_selector';
  }
  if ($form_id == 'node_pece_annotation_annotation_step_2_form') {
    $form['#attached']['library'][] = 'pece_annotations/pece_annotations';
    $form['field_annotation_analytic']['widget']['current']['#prefix'] = '<p>Select one Structured Analytic (Question Set) and Analytic (Question)</p>';
    if (isset($form["field_annotation_analytic"]["widget"]["current"]["items"][0]["replace_button"])) {
      $form["field_annotation_analytic"]["widget"]["current"]["items"][0]["replace_button"]["#attributes"]["class"] = [];
    }

  }
}

function pece_annotations_preprocess_node__pece_analytic__analytic_on_annotation_form(&$variables) {
  $variables['title'] = $variables['elements']['#node']->getTitle();
  $variables['question_set_title'] = $variables['elements']['#node']->field_analytic_question_set->entity->getName() ?? "";
}
