<?php
/**
 * @file
 * Code for the pece_profile feature.
 */

include_once 'pece_profile.functions.inc';
include_once 'pece_profile.features.inc';

/**
 * Implements hook_form_alter().
 */
function pece_profile_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('pece_artifacts')) {
    module_load_include('inc', 'pece_artifacts', 'pece_artifacts.functions');

    $artifacts = pece_artifacts_fetch_all();
    $is_node_form = $form['#node_edit_form'] && isset($form['#node']->type);
    $is_artifact_form = $is_node_form && in_array($form['#node']->type, $artifacts);

    if ($is_artifact_form) {
      array_unshift($form['#validate'], 'pece_profile_check_author');
    }
  }
}

/**
 * Validate function to check the authors field and fill the contributors
 * accourding the author name.
 */
function pece_profile_check_author(&$form, &$form_state) {
  global $user;
  $values = $form_state['values'];
  $user_profile = profile2_load_by_user($user);

  // Skip autofill the contributor field if current user is already the author.
  if (isset($user_profile['pece_profile_main'])) {
    $profile_wrapper = entity_metadata_wrapper('profile2', $user_profile['pece_profile_main']);
    if (isset($values['field_pece_authors']['und'][0]) &&
      $values['field_pece_authors']['und'][0]['name'] == $profile_wrapper->field_pece_full_name->value()) {
      return;
    };
  }

  // Skip autofill the contributor field if current user isn't contributor.
  if (!is_contributor($user) ||
      $values['field_pece_contributors']['und'][0]['target_id'] == $user->uid) {
    return;
  }
  // @TODO: Needs to support multilanguage.
  $value = array(LANGUAGE_NONE => array(array('target_id' => $user->uid)));
  form_set_value($form['field_pece_contributors'], $value, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_profile_form_user_register_form_alter(&$form, &$form_state) {
  // Hide the profile email field in order to autofill it based on the user's
  // account email.
  $form['profile_pece_profile_main']['field_pece_email']['#attributes']['class'][] = 'element-invisible';
  array_unshift($form['#validate'], 'pece_profile_user_register_form_validate');
}

function pece_profile_user_register_form_validate($form, &$form_state) {
  $email = $form_state['values']['mail'];
  // @TODO: Needs to support multilanguage.
  $element['#parents'] = array('profile_pece_profile_main', 'field_pece_email', LANGUAGE_NONE, 0, 'email');
  form_set_value($element, $email, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_profile_form_user_profile_form_alter(&$form, &$form_state) {
  // We're not using Panopoly's user fields.
  $form['field_user_about']['#access'] = FALSE;
}

/**
 * Implements hook_modules_enabled().
 *
 * This hook is implemented to assign some default permissions for PECE profile.
 * This has to be done in this hook to run after both features
 * and defaultconfig which power the functionality. Hopefully a more general solution
 * can be found. More information - http://drupal.org/node/1837312.
 */
function pece_profile_modules_enabled($modules) {

  // Only run this logic if we are executing as part of an install profile
  // and only for this particular module.
  if (drupal_installation_attempted() && in_array('pece_profile', $modules)) {

    // Define some permissions for the authentcated user role
    user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('view own pece_profile_main profile'));
    user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('edit own pece_profile_main profile'));
    user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('view any pece_profile_main profile'));
  }
}
