<?php
/**
 * @file
 * Code for the pece_artifacts_video feature.
 */

include_once 'pece_artifacts_video.features.inc';


/**
 * Implements hook_form_FORM_ID_alter().
 */
function pece_artifacts_video_form_pece_artifact_video_node_form_alter(&$form, &$form_state) {
  // PECE's artifact default form alter.
  pece_artifacts_alter_artifact_form($form, $form_state);

  if (module_exists('pece_profile')) {
    array_unshift($form['#validate'], 'pece_profile_check_author');
  }
}
