<?php
/**
 * @file
 * Code for the PECE Design Logic feature.
 */

include_once 'pece_design_logic.features.inc';

/**
 * Implements hook_pece_default_permissions().
 */
function pece_default_permissions() {
  $permissions = array();

  $permissions['all'] = array(
    'eck list design_logic design_logic entities' => TRUE,
    'eck view design_logic design_logic entities' => TRUE,
  );

  return $permissions;
}

/**
 * Implements hook_theme().
 */
function pece_design_logic_theme() {
  $path_to_module = drupal_get_path('module', 'pece_design_logic');

  return array(
    'design_logic__design_logic' => array(
      'render element' => 'elements',
      'template' => 'design-logic',
      'path' => $path_to_module . '/templates',
    ),
  );
}
