<?php
// Plugin definition
$plugin = array(
  'title' => 'Pond Double',
  'icon' => 'pece-pond.png',
  'category' => 'PECE',
  'theme' => 'pece_pond',
  'regions' => array(
    'header' => t('Header'),
    'column1' => t('Row 1: First Column'),
    'column2' => t('Row 1: Second Column'),
    'column3' => t('Row 1: Third Column'),
    'content' => t('Content'),
    'secondarycolumn1' => t('Row 2: First Column'),
    'secondarycolumn2' => t('Row 2: Second Column'),
    'secondarycolumn3' => t('Row 2: Third Column'),
    'footer' => t('Footer'),
  ),
);
