<?php
/**
 * @file
 * Code for the PECE About feature.
 */

Use \Drupal\Core\Link;

/**
 * Implements hook_theme().
 */
function pece_about_theme() {
  $path = \Drupal::service('extension.path.resolver')->getPath('module', 'pece_about') . '/templates';
  return [
    'about_pece' => [
      'render element' => 'children',
      'path' => $path,
      'template' => 'pece-about-block',
    ],
  ];
}

/**
 * Helper function to prepare About and About PECE block contents by adding
 * ellipsis and 'read more' link.
 */
function pece_about_trim_summary($summary, $more = TRUE, $alter = []) {
  if (empty($summary)) {
    return '';
  }
  $content = $summary;
  if (function_exists('views_trim_text')) {
    if (empty($alter)) {
      $alter = [
        'max_length' => NULL,
        'word_boundary' => TRUE,
        'ellipsis' => TRUE,
        'html' => TRUE,
      ];
    }
    $content = views_trim_text($alter, $summary);
  }

  if ($more !== FALSE) {
    $read_more_link = Link::fromTextAndUrl(t('Read more'), '/about');
    $read_more = $read_more_link->toRenderable();
    $read_more['#attribules']['class'] = 'read-mode';
    $content .= $read_more;
  }

  return $content;
}
