<?php
/**
 * @file
 * Installation code for the PECE About feature.
 */

/**
 * Configures a default about page.
 *
 * @return int
 *   Node id.
 */
function pece_about_install_default_page() {
  $file_path = \Drupal::service('extension.path.resolver')
    ->getPath('module', 'pece_about') . '/defaults/node-page-4806dbb2-39dc-4d1f-9b71-15eaaeaf5ac8.yml';
  $node = \Drupal::service('single_content_sync.importer')
    ->importFromFile($file_path);
  return $node->get('nid')->value;
}
