<?php
/**
 * @file
 * Code for the PECE Projects feature.
 */

include_once 'pece_substantive_logic.features.inc';

/**
 * Implements hook_form_ID_alter().
 */
function pece_substantive_logic_form_pece_sub_logic_node_form_alter(&$form, &$form_state) {
  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
  // We cannot allow the content to be authored by anonymous.
  $form['author']['name']['#required'] = TRUE;
}
