<?php
/**
 * @file
 * Code for the PECE Projects feature.
 */

include_once 'pece_substantive_logic.features.inc';

/**
 * Implements hook_form_ID_alter().
 */
function pece_substantive_logic_form_pece_sub_logic_node_form_alter(&$form, &$form_state) {
  $form['field_pece_start_end_date'][LANGUAGE_NONE][0]['#element_validate'][] = 'pece_substantive_logic_field_pece_start_end_date_validate';

  // Hide the comment settings fieldset.
  $form['comment_settings']['#access'] = FALSE;
}

/**
 * Implements function validade field.
 */
function pece_substantive_logic_field_pece_start_end_date_validate(&$element, &$form_state) {
  $value = $element['#value']['value']['date'];
  if (empty($value)) {
    form_set_error('field_pece_start_end_date][und][0][value][date', 'The first date is requerid.');
  }
}
